# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParentcraftService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ParentcraftService
  pod 'ACFloatingTextfield'
  pod 'Alamofire','5.0.2'
   pod 'IQKeyboardManagerSwift'
   pod 'SVProgressHUD'
   pod 'SDWebImage'
   pod 'Toast-Swift'
#   pod 'GoogleMaps'
#   pod 'GooglePlaces'
#   pod 'Cosmos'
#   pod 'Charts'
#   pod 'Firebase/Messaging','6.3.0'
#   pod 'Fabric', '~> 1.10.2'
#   pod 'Crashlytics', '~> 3.14.0'
  
 

end
